/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.DPersona;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.SEXO;

/**
 *
 * @author labc205
 */
public class FrmPersona extends javax.swing.JFrame {
    DPersona dP = new DPersona(); 
    /**
     * Creates new form FrmPersona
     */
    public FrmPersona() {
        initComponents();
        jbtnLIMPIAR.setToolTipText("Limpiar");
        jbtnAGREGAR.setToolTipText("Agregar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblID = new javax.swing.JLabel();
        jlblNOMBRES = new javax.swing.JLabel();
        jlblAPELLIDOS = new javax.swing.JLabel();
        jlblEMAIL = new javax.swing.JLabel();
        jlblSEXO = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jtfNOMBRE = new javax.swing.JTextField();
        jtfEMAIL = new javax.swing.JTextField();
        jtfAPELLIDOS = new javax.swing.JTextField();
        jcmbSEXO = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        jbtnLIMPIAR = new javax.swing.JButton();
        jbtnAGREGAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblREGISTRO = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblID.setText("ID");

        jlblNOMBRES.setText("NOMBRES");

        jlblAPELLIDOS.setText("APELLIDOS");

        jlblEMAIL.setText("EMAIL");

        jlblSEXO.setText("SEXO");

        jtfNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNOMBREActionPerformed(evt);
            }
        });

        jcmbSEXO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Hombre", "Mujer" }));

        jToolBar1.setRollover(true);

        jbtnLIMPIAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/img/Nuevo.png"))); // NOI18N
        jbtnLIMPIAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnLIMPIAR.setFocusable(false);
        jbtnLIMPIAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnLIMPIAR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnLIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLIMPIARActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnLIMPIAR);

        jbtnAGREGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Complementos/img/Guardar.png"))); // NOI18N
        jbtnAGREGAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAGREGAR.setFocusable(false);
        jbtnAGREGAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAGREGAR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAGREGARActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnAGREGAR);

        jtblREGISTRO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblREGISTRO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblAPELLIDOS)
                    .addComponent(jlblNOMBRES)
                    .addComponent(jlblID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblEMAIL)
                    .addComponent(jlblSEXO))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfAPELLIDOS)
                        .addComponent(jtfNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfEMAIL, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jcmbSEXO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblID)
                            .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblNOMBRES)
                            .addComponent(jtfNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblAPELLIDOS)
                            .addComponent(jtfAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblEMAIL)
                            .addComponent(jtfEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblSEXO)
                            .addComponent(jcmbSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNOMBREActionPerformed

    private void jbtnLIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLIMPIARActionPerformed
        // TODO add your handling code here:
        llenarTabla();
        limpiar();
    }//GEN-LAST:event_jbtnLIMPIARActionPerformed

    private void jbtnAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAGREGARActionPerformed
        // TODO add your handling code here:
        if (jtfID.getText().length()==0) {
        JOptionPane.showMessageDialog(this,
                "Necesita agregar el ID", "ERROR", JOptionPane.WARNING_MESSAGE);
        return;}
        
        if (jtfNOMBRE.getText().length()==0) {
        JOptionPane.showMessageDialog(this,
                "Necesita agregar el NOMBRE", "ERROR", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        int id = Integer.parseInt(jtfID.getText());
        String nom = jtfNOMBRE.getText();
        String ape = jtfAPELLIDOS.getText();
        String email = jtfEMAIL.getText();
        SEXO s;
        if (jcmbSEXO.getSelectedIndex() == 1) s = SEXO.Hombre;
        else s = SEXO.Mujer;
        
        int b = dP.agregarPersona(id, nom, ape, email, s);
        if (b==1) {
            JOptionPane.showMessageDialog(this, "Registro Agregado",
                    "Guardar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar...", "Guardar", JOptionPane.ERROR);
        }
        
        llenarTabla();
    }//GEN-LAST:event_jbtnAGREGARActionPerformed

    private void llenarTabla(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl = dP.getListPers();
        jtblREGISTRO.setModel(tbl);
    }
    
    private void limpiar() {
        jtfID.setText("");
        jtfNOMBRE.setText("");
        jtfAPELLIDOS.setText("");
        jtfEMAIL.setText("");
        jcmbSEXO.setSelectedIndex(0);
        jtfID.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtnAGREGAR;
    private javax.swing.JButton jbtnLIMPIAR;
    private javax.swing.JComboBox<String> jcmbSEXO;
    private javax.swing.JLabel jlblAPELLIDOS;
    private javax.swing.JLabel jlblEMAIL;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblNOMBRES;
    private javax.swing.JLabel jlblSEXO;
    private javax.swing.JTable jtblREGISTRO;
    private javax.swing.JTextField jtfAPELLIDOS;
    private javax.swing.JTextField jtfEMAIL;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfNOMBRE;
    // End of variables declaration//GEN-END:variables
}
